#!/bin/bash
                                                                                                                                  
# Fedora auto installation for rpmfusion
# Last updated Dec.11, 2022
# written by simmon
# www.nplob.com

version=`uname -r|cut -d 'c' -f 2|cut -d '.' -f 1`
echo "rpmfusion free release for F$version"
rpm -Uvh https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$version.noarch.rpm
echo "rpmfusion non-free release for F$version"
rpm -Uvh https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$version.noarch.rpm
