#!/bin/bash
                                                                                                                                  
# It is applied and used starting from the distribution version prior to F41.
# Fedora auto installation for rpmfusion
# Last updated May.31, 2025
# written by simmon
# www.nplob.com

version=`uname -r|cut -d 'c' -f 3|cut -d '.' -f 1`
echo "rpmfusion free release for F$version"
rpm -Uvh https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$version.noarch.rpm
echo "rpmfusion non-free release for F$version"
rpm -Uvh https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$version.noarch.rpm
